### PR TITLE
General Working

### LINKED ISSUE #4: Auto get new announcements and link

### LINKED ISSUE #7: Vue site for new polls and managing polls

### LINKED ISSUE #8: UI/UX design

### LINKED ISSUE #10: Events tab

### PR DESCRIPTION
**Pull request by InvertedOwl**
Closes #8 
Closes #4 
Closes #10 (Announcements will act like events tab (afaik?))

Current Functional...
- Announcements (Displaying)
- Youtube Feed (Need to find better way for API. Maybe manually put in video every time? Its crazy laggy)
- Polls (Displaying. Cant submit polls but that will be soon)

Needs work
- Week Schedule system isn't great and also doesn't work on Android
- The entire notifications thing. I haven't worked on it yet
- Home page feed needs to display the three category content
- Youtube feed clunky

### CODE REVIEW

**Comment by InvertedOwl** [comment]
Also, for some reason, my GC App Server repo is not considered a branch of the Green Canyon Computer Science's repo. They are two separate repos so I can't make a pull request on the server. 🤷‍♀️

**Comment by shane-andrus** [comment]
#approved

**Comment by shane-andrus** [comment]
Can I merge>

**Review by shane-andrus — APPROVED** [review]

**Comment by InvertedOwl** [comment]
> Can I merge>

Almost finished with notifications. I'll finish it today

**Pull request merged**
